<?php

/**
 * Implements hook_og_features_registry() for the node module.
 */
function ejrst_og_features_og_features_registry() {
  $options = array(
    'discussion' => array(
      'title' => t('Discussions'),
      'entity' => array(
        'node' => array(
          'discussion',
        ),
      ),
      'page' => array(
        'type' => 'view',
        'name' => 'group_discussions',
      ),
    ),
    'blog' => array(
      'title' => t('Blogs'),
      'entity' => array(
        'node' => array(
          'blog',
        ),
      ),
      'page' => array(
        'type' => 'view',
        'name' => 'group_blog',
      ),
    ),
    'wiki' => array(
      'title' => t('Wiki'),
      'entity' => array(
        'node' => array(
          'wiki',
        ),
      ),
      'page' => array(
        'type' => 'view',
        'name' => 'group_wiki',
      ),
    ),
    'events' => array(
      'title' => t('Events'),
      'entity' => array(
        'node' => array(
          'event',
        ),
      ),
      'page' => array(
        'type' => 'view',
        'name' => 'group_calendar',
      ),
    ),
    'note' => array(
      'title' => t('Notes'),
      'entity' => array(
        'node' => array(
          'note',
        ),
      ),
      'page' => array(
        'type' => 'view',
        'name' => 'group_notes',
      ),
    ),
    'task' => array(
      'title' => t('Tasks'),
      'entity' => array(
        'node' => array(
          'task',
        ),
      ),
      'page' => array(
        'type' => 'view',
        'name' => 'group_tasks',
      ),
    ),
    'news' => array(
      'title' => t('News'),
      'entity' => array(
        'node' => array(
          'news',
        ),
      ),
      'page' => array(
        'type' => 'view',
        'name' => 'group_news',
      ),
    ),
  );
  return $options;
}

/**
 * Implements hook_views_api().
 */
function ejrst_og_features_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'ejrst_og_features') . '/views/',
  );
}