<?php

/**
 * Implements hook_og_features_registry() for the node module.
 */
function ejrst_og_features_og_features_registry() {
  $options = array(
    'discussion' => array(
      'title' => t('Discussions'),
      'entity' => array(
        'node' => array(
          'discussion',
        ),
      ),
    ),
    'wiki' => array(
      'title' => t('Wiki'),
      'entity' => array(
        'node' => array(
          'wiki',
        ),
      ),
    ),
    'events' => array(
      'title' => t('Events'),
      'entity' => array(
        'node' => array(
          'event',
        ),
      ),
    ),
    'note' => array(
      'title' => t('Notes'),
      'entity' => array(
        'node' => array(
          'note',
        ),
      ),
    ),
    'task' => array(
      'title' => t('Tasks'),
      'entity' => array(
        'node' => array(
          'task',
        ),
      ),
    ),
    'news' => array(
      'title' => t('News'),
      'entity' => array(
        'node' => array(
          'news',
        ),
      ),
    ),
  );
  return $options;
}